apiVersion: ketch.io/v1alpha1
kind: App
metadata:
  name: podinfo-prod
spec:
  forProvider:
    name: podinfo-prod
    image: ghcr.io/stefanprodan/podinfo:6.0.3
    framework: prod-framework
    ports: [9898]
    units: 2
